import bug from "../../../assets/projects/bug.webp";
import quiero from "../../../assets/projects/quiero.webp";
import micropack from "../../../assets/projects/micropack.webp";
import norush from "../../../assets/projects/norush.webp";
import cad from "../../../assets/projects/cad.webp";
import random from "../../../assets/projects/random.webp";

const industrialDesigns = [
  {
    type: "industrial",
    title: "NoRush",
    description: "Strong and light Tyvek® wallets",
    imgUrl: norush,
    info: "NoRush is a project that I created with my partner. The idea was to make the strongest, recyclable  and cool wallet on the market. I developed 100% of the product and we figured out how to produce them at home.",
    repo: "",
    video: "",
    test: "",
    pictures: [
      "norush-1.png",
      "norush-2.png",
      "norush-3.png",
      "norush-4.png",
      "norush-5.png",
    ],
    client: "",
    company: "NoRush",
    stack: "Photoshop, Illustrator, Corel Draw",
  },
  {
    type: "industrial",
    title: "Grupo Quiero",
    description: "Retail Design, Branding, Look & Feel",
    imgUrl: quiero,
    info: "Working at Grupo Quiero was the best experience I ever had as an Industrial Designer. There, I had the opportunity to work with the biggest companies in the world developing projects for all LATAM. I have to say that it is hard to select just a few examples after years with them.",
    repo: "",
    video: "",
    test: "",
    pictures: [
      "quiero-1.png",
      "quiero-2.png",
      "quiero-3.png",
      "quiero-4.png",
      "quiero-5.png",
    ],
    client: "L'Oréal Paris, Movistar and more",
    company: "Grupo Quiero",
    stack: "Photoshop, Illustrator, Rhinoceros 3D, 3DsMax, Vray",
  },
  {
    type: "industrial",
    title: "Micropack",
    description: "Retail Design with micro-corrugated cardboards",
    imgUrl: micropack,
    info: "It wasn't so long my stay at Micropack, but my heart is there as it was my first professional job. The designs I am showing you are not mine because actually I was in charge of developing the prototypes and testing.",
    repo: "",
    video: "",
    test: "",
    pictures: ["micro-1.png", "micro-2.png", "micro-3.png"],
    client: "Unilever, Coca-Cola and more",
    company: "Micropack",
    stack: "Photoshop, Illustrator, Corel Draw",
  },
  {
    type: "industrial",
    title: "Engineering",
    description: "CAD systems and technical draws",
    imgUrl: cad,
    info: "In many countries the Industrial Designers are considered  engineers because we can make technical drawings, physics  calculations and we have knowledge about industrial processes  and technologies. We start a project from the sketches to the testing of prototypes and their final massive production.",
    repo: "",
    video: "",
    test: "",
    pictures: ["cad-1.png", "cad-2.png", "cad-3.png", "cad-4.png", "cad-5.png"],
    client: "L'Oréal Paris, New Balance and more",
    company: "Grupo Quiero, Ikea, freelancer",
    stack: "Autocad, Illustrator, Corel Draw, Solidworks, Rhinoceros 3D",
  },
  {
    type: "industrial",
    title: "BUG",
    description: "A mechanical leaf sweeper",
    imgUrl: bug,
    info: "Project BUG started as my final project at the University and then it became my personal project. I have to confess that I am not working on it any more but it is still great!.",
    repo: "",
    video:
      "https://www.youtube.com/watch?v=gl_RSSi1YCo&ab_channel=FrancoAmoroso",
    test: "",
    pictures: ["bug-1.png", "bug-2.png", "bug-3.png", "bug-4.png"],
    client: "",
    company: "Freelancer",
    stack: "Rhinoceros 3D, Solidworks, Keyshot, Photoshop, Corel Draw",
  },
  {
    type: "industrial",
    title: "Product design",
    description: "A bit more about my projects",
    imgUrl: random,
    info: "This is a selection of some other projects I have been through. Most of them are concepts that are never seen in the real world, but they were very important in my career.",
    repo: "",
    video: "",
    test: "",
    pictures: [
      "random-1.png",
      "random-2.png",
      "random-3.png",
      "random-4.png",
      "random-5a.png",
      "random-5b.png",
    ],
    client: "EstudioFIX, Pinkmask and more",
    company: "",
    stack: "Rhinoceros 3D, 3D-Max, Vray, Photoshop, Corel Draw",
  },
];

export default industrialDesigns;
