import coolxMain from "../../../assets/projects/coolx-main.webp";
import digiartMain from "../../../assets/projects/digiart-main.webp";
import netfilmMovies from "../../../assets/projects/netfilm-movies.webp";
import calc from "../../../assets/projects/calc.webp";
import videoplayer from "../../../assets/projects/videoplayer.webp";
import portfolio from "../../../assets/projects/portfolio.webp";
import jokesapi from "../../../assets/projects/jokesapi.webp";
import safeguru from "../../../assets/projects/safeguru.webp";

const webProjects = [
  {
    type: "web",
    title: "Safeguru",
    description: "Online industrial safety and PPE suppliers",
    imgUrl: safeguru,
    info: "Currently, I am working at A-SAFE Digital as a Junior Front-end Developer. The company is part of a group of British firms specializing in the development and distribution of safety systems for industrial plants. The Safeguru e-commerce platform is one among several projects in which my colleagues and I are involved. While the project is still in development and growth, it is already operational online in Spain and the United Kingdom, with plans for expansion to more countries in the near future.",
    repo: "",
    video: "",
    test: "https://safeguru.co.uk/",
    pictures: ["safeguru2.webp", "safeguru3.webp", "safeguru4.webp"],
    client: "Safeguru",
    company: "A-SAFE Digital",
    stack: "Next.js, TypeScript, Styled Components (migrating to Tailwind)",
  },
  {
    type: "web",
    title: "The Jokes API",
    description: "A React app with hundreds of random jokes",
    imgUrl: jokesapi,
    info: 'The Jokes API is a web application that takes you on a journey through a world of randomly selected jokes. With the capability to present jokes with a simple click, the app offers a continuous source of amusement. Users can also rate jokes to provide feedback and filter them by categories based on personal preferences. Additionally, if users feel inclined, they can contribute to the collection by submitting their own jokes. In essence, "The Jokes API" serves as a virtual platform to enjoy, evaluate, and share an endless array of laughter, with jokes selected randomly rather than being auto-generated.',
    repo: "https://github.com/Frankovg/theJokesAPI",
    video: "https://youtu.be/ROJoLYIi0ZA?si=KLRTUGr1NXFaUUWj",
    test: "",
    pictures: ["thejokesapi.webp"],
    client: "",
    company: "",
    stack: "React.js, JavaScript, Bootstrap, Sass, MySQL, Node.js",
  },
  {
    type: "web",
    title: "My personal web",
    description: "A React web deployed by Firebase",
    imgUrl: portfolio,
    info: "Promptly following the completion of my Full-Stack Web Development bootcamp, I embarked on the creation of this website. The primary objective behind this endeavor is to present a platform for sharing my biography and showcasing a selection of my portfolio pieces. I hope you like it!",
    repo: "",
    video: "",
    test: "",
    pictures: ["franco-home.png"],
    client: "",
    company: "",
    stack: "React.js, JavaScript, Bootstrap, Sass, Firebase",
  },
  {
    type: "web",
    title: "Netfilm",
    description: "A Netflix clone made with React",
    imgUrl: netfilmMovies,
    info: `Netfilm stands as a fully responsive emulation of Netflix, meticulously crafted using React.js and Redux. Notably, for the backend, Firebase was harnessed to facilitate user authentication, streamlining the development process. The movie API employed originates from the renowned "The Movie Database" (TMDB), enhancing the project's content and functionality.`,
    repo: "https://github.com/Frankovg/netfilm",
    video:
      "https://www.youtube.com/watch?v=g6nDENxjK3c&ab_channel=FrancoAmoroso",
    test: "",
    pictures: ["netfilm-login.png", "netfilm-user.png", "netfilm-home.png"],
    client: "",
    company: "",
    stack: "React.js, Redux, JavaScript, Bootstrap, Sass, Firebase",
  },
  {
    type: "web",
    title: "Coolx - MVP",
    description: "Minimum viable product development",
    imgUrl: coolxMain,
    info: "The application is designed to enhance the management of forestry projects by leveraging AI and machine learning technologies. It aims to provide expedited and highly accurate information regarding land utilization and forest inventory, thereby significantly improving overall efficiency.",
    repo: "https://github.com/Frankovg/proyecto_final_socratech",
    video:
      "https://www.youtube.com/watch?v=BGOv_VQLyyU&t=8s&ab_channel=Socratech",
    test: "",
    pictures: ["coolx-projects.png", "coolx-admin.png", "coolx-user.png"],
    client: "Coolx",
    company: "Socratech",
    stack: "React.js, JavaScript, Node.js, Express, MySQL, Bootstrap, Sass",
  },
  {
    type: "web",
    title: "DigiArt",
    description: "A social network for digital artists",
    imgUrl: digiartMain,
    info: "This represents my independent full-stack endeavor, developed over the span of 8 weeks during my bootcamp journey. Crafted solely by me, this project was successfully completed in a mere 3 days. Functioning as an assessment tool, it allows bootcamp participants to gauge their proficiency midway through the program, providing insights into their acquired knowledge.",
    repo: "https://github.com/Frankovg/proyecto_socratech",
    video: "https://www.youtube.com/watch?v=x851u6-utEU&ab_channel=Socratech",
    test: "",
    pictures: ["digiart-ux.png", "digiart-user0.png", "digiart-user1.png"],
    client: "",
    company: "Socratech",
    stack: "HTML5, CSS3, Bootstrap, Sass, JavaScript, Node.js, Express, MySQL",
  },

  {
    type: "web",
    title: "Calculator",
    description: "Built with JavaScript",
    imgUrl: calc,
    info: "A calculator meticulously crafted from scratch using JavaScript. This application adeptly handles fundamental mathematical operations such as addition, subtraction, multiplication, and division. Notably, the calculator's functionalities are implemented using pure Vanilla JavaScript, devoid of any reliance on the 'eval()' function for computation.",
    repo: "https://github.com/Frankovg/Calculator_JS",
    video: "",
    test: "https://frankovg.github.io/Calculator_JS/",
    pictures: ["calculator.png"],
    client: "",
    company: "",
    stack: "JavaScript, HTML5, CSS3, Sass",
  },
  {
    type: "web",
    title: "Video Player",
    description: "Made from scratch with JavaScript",
    imgUrl: videoplayer,
    info: "The Video Player serves as an educational exercise for mastering Vanilla JavaScript. All functionalities within this project are meticulously crafted using JavaScript. Automatic detection of video duration is incorporated seamlessly. Noteworthy features include the ability to advance or rewind by 5 seconds, as well as play and pause functions. Additionally, the timebar is interactive, allowing users to adjust the playback position simply by clicking on it.",
    repo: "https://github.com/Frankovg/video-player",
    video: "",
    test: "https://frankovg.github.io/video-player/",
    pictures: ["videoplayer.png"],
    client: "",
    company: "",
    stack: "JavaScript, HTML5, CSS3",
  },
];

export default webProjects;
